### ISSUE TITLE
If the method has no params and no result to return, the will be nil pointer dereference

### ISSUE THREAD

**Issue by ybdx** [corsc/go-tools#25]
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x1195f70]

such as if your interface like this 
`
type test interface {
MyTest()
}
`

the error code is 
`
func extractParamsAndResults(fnDesl *ast.FuncType) ([]MethodField, []MethodField) {
	params := extractFieldsFromAst(fnDesl.Params.List)
	results := extractFieldsFromAst(fnDesl.Results.List)

	return params, results
}
`

you should change it like this
`
func extractParamsAndResults(fnDesl *ast.FuncType) ([]MethodField, []MethodField) {
	var params []MethodField
	var results []MethodField
	if fnDesl.Params.List != nil {
		params = extractFieldsFromAst(fnDesl.Params.List)
	}
	
	if fnDesl.Results.List != nil {
		results = extractFieldsFromAst(fnDesl.Results.List)
	}
	
	return params, results
}
`

**Comment by corsc** [comment]
Thanks for the bug report.  I hope to make a fix soon.

**Comment by corsc** [comment]
Merged and push to master.  Thanks
